"""create brands, models, cars

Revision ID: 5644fef99cd1
Revises: 
Create Date: 2025-08-16 12:57:27.803937

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5644fef99cd1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('brands',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome_marca', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome_marca', name='UQ_brand_nome')
    )
    op.create_table('models',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('marca_id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=120), nullable=False),
    sa.Column('valor_fipe', sa.DECIMAL(precision=12, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['marca_id'], ['brands.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome', 'marca_id', name='UQ_model_nome_brand')
    )
    with op.batch_alter_table('models', schema=None) as batch_op:
        batch_op.create_index('IDX_model_brand', ['marca_id'], unique=False)

    op.create_table('cars',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('timestamp_cadastro', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('modelo_id', sa.Integer(), nullable=False),
    sa.Column('ano', sa.Integer(), nullable=False),
    sa.Column('combustivel', sa.Enum('GASOLINA', 'ETANOL', 'FLEX', 'DIESEL', 'HIBRIDO', 'ELETRICO', name='cars_combustivel_enum'), nullable=False),
    sa.Column('num_portas', sa.Integer(), nullable=False),
    sa.Column('cor', sa.String(length=40), nullable=False),
    sa.CheckConstraint('"ano" BETWEEN 1950 AND 2100', name='CHK_car_ano'),
    sa.CheckConstraint('"combustivel" IN (\'GASOLINA\',\'ETANOL\',\'FLEX\',\'DIESEL\',\'HIBRIDO\',\'ELETRICO\')', name='CHK_car_combustivel'),
    sa.CheckConstraint('"num_portas" BETWEEN 2 AND 6', name='CHK_car_num_portas'),
    sa.ForeignKeyConstraint(['modelo_id'], ['models.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cars', schema=None) as batch_op:
        batch_op.create_index('IDX_car_createdAt', ['timestamp_cadastro'], unique=False)
        batch_op.create_index('IDX_car_model', ['modelo_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cars', schema=None) as batch_op:
        batch_op.drop_index('IDX_car_model')
        batch_op.drop_index('IDX_car_createdAt')

    op.drop_table('cars')
    with op.batch_alter_table('models', schema=None) as batch_op:
        batch_op.drop_index('IDX_model_brand')

    op.drop_table('models')
    op.drop_table('brands')
    # ### end Alembic commands ###
