services:
  db:
    image: postgres:16-alpine
    container_name: wswork_db
    environment:
      POSTGRES_DB: ${DB_NAME:-wswork_cars}
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASS:-postgres}
    ports:
      - '${DB_PORT:-5432}:5432'
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test:
        [
          'CMD-SHELL',
          'pg_isready -U ${DB_USER:-postgres} -d ${DB_NAME:-wswork_cars}',
        ]
      interval: 5s
      timeout: 3s
      retries: 20

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: wswork_api
    depends_on:
      db:
        condition: service_healthy
    environment:
      PORT: 3000
      CORS_ORIGINS: ${CORS_ORIGINS:-http://localhost:5173,http://localhost:3001}
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: ${DB_USER:-postgres}
      DB_PASS: ${DB_PASS:-postgres}
      DB_NAME: ${DB_NAME:-wswork_cars}
      RUN_SEED: ${RUN_SEED:-false}
    ports:
      - '3000:3000'

volumes:
  db_data:
