import { InputCar } from './seed';

const startTs = 1_717_000_000;
let seq = 0;

export const input = {
  cars: [
    {
      id: 1,
      timestamp_cadastro: startTs + 60 * seq++,
      modelo_id: 100,
      ano: 2023,
      combustivel: 'DIESEL',
      num_portas: 4,
      cor: 'BRANCO',
      nome_modelo: 'SW4 Diamond',
      valor: '390.000,00',
    },
    {
      id: 2,
      timestamp_cadastro: startTs + 60 * seq++,
      modelo_id: 101,
      ano: 2024,
      combustivel: 'GASOLINA',
      num_portas: 4,
      cor: 'PRETO',
      nome_modelo: 'RS6 Avant 4.0 TFSI Quattro',
      valor: '1.180.000,00',
    },
    {
      id: 3,
      timestamp_cadastro: startTs + 60 * seq++,
      modelo_id: 102,
      ano: 2024,
      combustivel: 'HIBRIDO',
      num_portas: 4,
      cor: 'PRETO',
      nome_modelo: 'Range Rover Sport',
      valor: '970.000,00',
    },

    {
      id: 4,
      timestamp_cadastro: startTs + 60 * seq++,
      modelo_id: 103,
      ano: 2024,
      combustivel: 'ELETRICO',
      num_portas: 4,
      cor: 'PRATA',
      nome_modelo: 'Seal',
      valor: '298.000,00',
    },
    {
      id: 5,
      timestamp_cadastro: startTs + 60 * seq++,
      modelo_id: 104,
      ano: 2023,
      combustivel: 'DIESEL',
      num_portas: 4,
      cor: 'CINZA',
      nome_modelo: 'Defender 110',
      valor: '719.000,00',
    },
    {
      id: 6,
      timestamp_cadastro: startTs + 60 * seq++,
      modelo_id: 105,
      ano: 2023,
      combustivel: 'GASOLINA',
      num_portas: 2,
      cor: 'AZUL',
      nome_modelo: '911 GT3',
      valor: '2.550.000,00',
    },

    {
      id: 7,
      timestamp_cadastro: startTs + 60 * seq++,
      modelo_id: 106,
      ano: 2023,
      combustivel: 'GASOLINA',
      num_portas: 4,
      cor: 'BRANCO',
      nome_modelo: '1500 Rebel',
      valor: '489.000,00',
    },
    {
      id: 8,
      timestamp_cadastro: startTs + 60 * seq++,
      modelo_id: 107,
      ano: 2023,
      combustivel: 'GASOLINA',
      num_portas: 2,
      cor: 'CINZA',
      nome_modelo: 'Mustang',
      valor: '539.000,00',
    },
    {
      id: 9,
      timestamp_cadastro: startTs + 60 * seq++,
      modelo_id: 108,
      ano: 2024,
      combustivel: 'GASOLINA',
      num_portas: 4,
      cor: 'BRANCO',
      nome_modelo: 'Macan GTS 2.9',
      valor: '710.000,00',
    },

    {
      id: 10,
      timestamp_cadastro: startTs + 60 * seq++,
      modelo_id: 109,
      ano: 2023,
      combustivel: 'GASOLINA',
      num_portas: 4,
      cor: 'VERMELHO',
      nome_modelo: 'Civic Type-R',
      valor: '429.000,00',
    },
    {
      id: 11,
      timestamp_cadastro: startTs + 60 * seq++,
      modelo_id: 110,
      ano: 2024,
      combustivel: 'GASOLINA',
      num_portas: 4,
      cor: 'BRANCO',
      nome_modelo: 'Macan',
      valor: '300.000,00',
    },
    {
      id: 12,
      timestamp_cadastro: startTs + 60 * seq++,
      modelo_id: 111,
      ano: 2024,
      combustivel: 'ELETRICO',
      num_portas: 4,
      cor: 'AZUL',
      nome_modelo: 'i4 Gran Coupé',
      valor: '567.000,00',
    },

    {
      id: 13,
      timestamp_cadastro: startTs + 60 * seq++,
      modelo_id: 112,
      ano: 2023,
      combustivel: 'GASOLINA',
      num_portas: 4,
      cor: 'PRETO',
      nome_modelo: 'GR Corolla',
      valor: '409.000,00',
    },
    {
      id: 14,
      timestamp_cadastro: startTs + 60 * seq++,
      modelo_id: 113,
      ano: 2024,
      combustivel: 'GASOLINA',
      num_portas: 2,
      cor: 'BRANCO',
      nome_modelo: 'M2 Competition',
      valor: '719.000,00',
    },
    {
      id: 15,
      timestamp_cadastro: startTs + 60 * seq++,
      modelo_id: 114,
      ano: 2024,
      combustivel: 'GASOLINA',
      num_portas: 4,
      cor: 'LARANJA',
      nome_modelo: 'Ranger Raptor',
      valor: '459.000,00',
    },

    {
      id: 16,
      timestamp_cadastro: startTs + 60 * seq++,
      modelo_id: 115,
      ano: 2021,
      combustivel: 'HIBRIDO',
      num_portas: 4,
      cor: 'BRANCO',
      nome_modelo: 'Panamera 4S E-Hybrid',
      valor: '922.000,00',
    },
    {
      id: 17,
      timestamp_cadastro: startTs + 60 * seq++,
      modelo_id: 116,
      ano: 2024,
      combustivel: 'GASOLINA',
      num_portas: 4,
      cor: 'PRETO',
      nome_modelo: 'X6 M Competition',
      valor: '1.029.000,00',
    },
    {
      id: 18,
      timestamp_cadastro: startTs + 60 * seq++,
      modelo_id: 117,
      ano: 2024,
      combustivel: 'GASOLINA',
      num_portas: 4,
      cor: 'CINZA',
      nome_modelo: 'Cayenne Turbo GT',
      valor: '1.280.000,00',
    },
  ] as InputCar[],
};
